routes/web.php
<?php

// use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Route::resource('address', 'App\Http\Controllers\AddressController');

app/Models/Address.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Address extends Model
{
    use SoftDeletes;

    protected $table = "address";
    protected $fillable = [
        'apt_number',
        'street',
        'section',
        'postcode',
        'city',
        'state'       
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AddressController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Address;

class AddressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $address = Address::all();

        return view('address.index', compact('address'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('address.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $address = new Address([
            'apt_number' => "No " . $request->apt_number,
            'street' => $request->street,
            'section' => $request->section,
            'postcode' => $request->postcode,
            'city' => $request->city,
            'state' => $request->state
    
        ]);

        $address->save();
        return redirect('/address')->with('success', 'Address successfully saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $address = Address::findOrFail($id);

        return view('address.edit', compact('address'));    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $address = Address::findOrFail($id);
        $address->apt_number =  $request->apt_number;
        $address->street = $request->street;
        $address->section = $request->section;
        $address->postcode = $request->postcode;
        $address->city = $request->city;
        $address->state = $request->state;

        $address->save();

        return redirect('/address')->with('success', 'Address updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $address = Address::find($id);
        $address->delete();

        return redirect('/address')->with('success', 'Address deleted!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/address/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Assignment</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="jumbotron text-center">
  <h4>Add new address</h4>
</div>
  
<div class="container">
<form method="post" action="{{ route('address.store') }}">
          @csrf
          <div class="form-group">    
              <label for="apt_number">Unit Number:</label>
              <input type="text" class="form-control" name="apt_number" placeholder="No."/>
          </div>

          <div class="form-group">
              <label for="street">Street:</label>
              <input type="text" class="form-control" name="street" placeholder="“Jalan ”, “Jln ”, “Lorong ”, “Persiaran”,"/>
          </div>

          <div class="form-group">
              <label for="section">Section:</label>
              <input type="text" class="form-control" name="section"/>
          </div>
          <div class="form-group">
              <label for="postcode">Postcode:</label>
              <input type="text" class="form-control" name="postcode"/>
          </div>
          <div class="form-group">
              <label for="city">City:</label>
              <select name="city" id="city">
                <option value="Kuala Terengganu">Kuala Terengganu</option>
                <option value="Kuala Lumpur">Kuala Lumpur</option>
                <option value="Kajang">Kajang</option>
                <option value="Bangi">Bangi</option>
                <option value="Damansara">Damansara</option>
                <option value="Petaling Jaya">Petaling Jaya</option>
                <option value="Puchong">Puchong</option>
                <option value="Subang Jaya">Subang Jaya</option>
                <option value="Cyberjaya">Cyberjaya</option>
                <option value="Putrajaya">Putrajaya</option>
                <option value="Mantin">Mantin</option>
                <option value="Kuching">Kuching</option>
                <option value="Seremban">Seremban</option>
              </select>
              <!-- <input type="text" class="form-control" name="city"/> -->
          </div>
          <div class="form-group">
              <label for="state">State:</label>
              <select name="city" id="city">
                <option value="Selangor">Selangor</option>
                <option value="Terengganu">Terengganu</option>
                <option value="Pahang">Pahang</option>
                <option value="Kelantan">Kelantan</option>
                <option value="Melaka">Melaka</option>
                <option value="Pulau Pinang">Pulau Pinang</option>
                <option value="Kedah">Kedah</option>
                <option value="Johor">Johor</option>
                <option value="Perlis">Perlis</option>
                <option value="Sabah">Sabah</option>
                <option value="Sarawak">Sarawak</option>
              </select>
              <!-- <input type="text" class="form-control" name="state"/> -->
          </div>                         
          <button type="submit" class="btn btn-primary-outline">Submit</button>
      </form>
</div>

</body>
</html>

resources/views/address/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Assignment</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="jumbotron text-center">
  <h4>Update new address</h4>
</div>
  
<div class="container">
<form method="post" action="{{ route('address.update', $address->id) }}">
          @method('PUT')
          @csrf
          <div class="form-group">    
              <label for="apt_number">Unit Number:</label>
              <input type="text" class="form-control" name="apt_number" placeholder="No."value={{ $address->apt_number }} />
          </div>

          <div class="form-group">
              <label for="street">Street:</label>
              <input type="text" class="form-control" name="street" placeholder="“Jalan ”, “Jln ”, “Lorong ”, “Persiaran”," value={{ $address->street }}/>
          </div>

          <div class="form-group">
              <label for="section">Section:</label>
              <input type="text" class="form-control" name="section" value={{ $address->section }}/>
          </div>
          <div class="form-group">
              <label for="postcode">Postcode:</label>
              <input type="text" class="form-control" name="postcode" value={{ $address->postcode }}/>
          </div>
          <div class="form-group">
              <label for="city">City:</label>
              <select name="city" id="city" value={{ $address->city }}>
                <option value="kt">Kuala Terengganu</option>
                <option value="kl">Kuala Lumpur</option>
                <option value="kjg">Kajang</option>
                <option value="bng">Bangi</option>
                <option value="dam">Damansara</option>
                <option value="pj">Petaling Jaya</option>
                <option value="puc">Puchong</option>
                <option value="subj">Subang Jaya</option>
                <option value="cbj">Cyberjaya</option>
                <option value="puj">Putrajaya</option>
                <option value="mtn">Mantin</option>
                <option value="kuc">Kuching</option>
                <option value="ser">Seremban</option>
              </select>
              <!-- <input type="text" class="form-control" name="city"/> -->
          </div>
          <div class="form-group">
              <label for="state">State:</label>
              <select name="city" id="city" value={{ $address->state }}>
                <option value="Selangor">Selangor</option>
                <option value="Terengganu">Terengganu</option>
                <option value="Pahang">Pahang</option>
                <option value="Kelantan">Kelantan</option>
                <option value="Melaka">Melaka</option>
                <option value="Pulau Pinang">Pulau Pinang</option>
                <option value="Kedah">Kedah</option>
                <option value="Johor">Johor</option>
                <option value="Perlis">Perlis</option>
                <option value="Sabah">Sabah</option>
                <option value="Sarawak">Sarawak</option>
              </select>
              <!-- <input type="text" class="form-control" name="state"/> -->
          </div>                         
          <button type="submit" class="btn btn-primary-outline">Update</button>
      </form>
</div>

</body>
</html>

resources/views/address/index.blade.php
@extends('base')

@section('main')
<div class="row">
<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>

<div class="col-sm-12">
    <h1 class="display-3">Address</h1> 
    <div>
    <a style="margin: 19px;" href="{{ route('address.create')}}" class="btn btn-primary">New address</a>
    </div>  

  <table class="table table-striped">
    <thead>
        <tr>
          <td>No.</td>
          <td>Address</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($address as $address)
        <tr>
            <td>{{$address->id}}</td>
            <td>
            {{$address->apt_number ?? '-' }} 
            {{$address->street ?? '-' }} 
            {{$address->section ?? '-' }} 
            {{$address->postcode ?? '-' }} 
            {{$address->city ?? '-' }} 
            {{$address->state ?? '-' }}
            </td>
            <td>
                <a href="{{ route('address.edit',$address->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('address.destroy', $address->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
</div>
@endsection

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Laravel 7 & MySQL CRUD Tutorial</title>
  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
  <div class="container">
    @yield('main')
  </div>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>